<?php
// This file is part of Moodle - http://moodle.org/
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

/**
 * Upgrade steps for mod_learningapp.
 *
 * @package     mod_learningapp
 * @copyright   2026 lasjoh-toho
 * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

/**
 * Execute mod_learningapp upgrade from the given old version.
 *
 * @param int $oldversion
 * @return bool
 */
function xmldb_learningapp_upgrade($oldversion) {
    global $DB;

    $dbman = $DB->get_manager();

    if ($oldversion < 2026090301) {
        // Some early installs of this plugin ended up without the
        // learningapp_submissions table (e.g. an interrupted or partial
        // install run before this table existed in db/install.xml).
        // Create it now if it is still missing, matching the definition
        // in db/install.xml exactly.
        $table = new xmldb_table('learningapp_submissions');

        $table->add_field('id', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, XMLDB_SEQUENCE, null);
        $table->add_field('learningappid', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, null);
        $table->add_field('userid', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, null);
        $table->add_field('grade', XMLDB_TYPE_NUMBER, '10, 2', null, XMLDB_NOTNULL, null, '0');
        $table->add_field('timesubmitted', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, '0');

        $table->add_key('primary', XMLDB_KEY_PRIMARY, ['id']);
        $table->add_key('learningappid', XMLDB_KEY_FOREIGN, ['learningappid'], 'learningapp', ['id']);
        $table->add_key('userid', XMLDB_KEY_FOREIGN, ['userid'], 'user', ['id']);

        $table->add_index('learningapp_user_idx', XMLDB_INDEX_UNIQUE, ['learningappid', 'userid']);

        if (!$dbman->table_exists($table)) {
            $dbman->create_table($table);
        }

        upgrade_mod_savepoint(true, 2026090301, 'learningapp');
    }

    if ($oldversion < 2026090304) {
        // Some installs of this plugin ended up with a learningapp table
        // that is missing one or more columns entirely (observed: the
        // externalurl column did not exist at all, causing form data to be
        // silently discarded on save with no error, since Moodle's DB layer
        // ignores properties that don't match a real column). This step
        // checks every column defined in db/install.xml and adds whichever
        // ones are missing on this site.
        //
        // Columns are intentionally added WITHOUT a NOT NULL constraint
        // (even where db/install.xml specifies one for a fresh install),
        // because ALTER TABLE ... ADD COLUMN ... NOT NULL can fail outright
        // on a table that already contains rows unless every existing row
        // gets a default value the storage engine accepts for that column
        // type (which is not reliably possible for TEXT columns in MySQL).
        // A nullable column is safe here and the plugin code already copes
        // with empty/missing values.
        $table = new xmldb_table('learningapp');

        $expectedfields = [
            new xmldb_field('course', XMLDB_TYPE_INTEGER, '10', null, null, null, null),
            new xmldb_field('name', XMLDB_TYPE_CHAR, '255', null, null, null, null),
            new xmldb_field('intro', XMLDB_TYPE_TEXT, null, null, null, null, null),
            new xmldb_field('introformat', XMLDB_TYPE_INTEGER, '4', null, null, null, '1'),
            new xmldb_field('externalurl', XMLDB_TYPE_TEXT, null, null, null, null, null),
            new xmldb_field('storelocally', XMLDB_TYPE_INTEGER, '1', null, null, null, '0'),
            new xmldb_field('grademax', XMLDB_TYPE_NUMBER, '10, 2', null, null, null, '100'),
            new xmldb_field('timecreated', XMLDB_TYPE_INTEGER, '10', null, null, null, '0'),
            new xmldb_field('timemodified', XMLDB_TYPE_INTEGER, '10', null, null, null, '0'),
        ];

        if ($dbman->table_exists($table)) {
            foreach ($expectedfields as $field) {
                if (!$dbman->field_exists($table, $field)) {
                    $dbman->add_field($table, $field);
                }
            }
        }

        upgrade_mod_savepoint(true, 2026090304, 'learningapp');
    }

    if ($oldversion < 2026090500) {
        // Local snapshots generated by earlier plugin versions (<=1.3.0) can
        // be badly broken: the nested show.php exercise wasn't embedded at
        // all before 1.3.0, and before this version, a sub-resource fetch
        // that failed (e.g. a hotlink-protected font returning an HTML
        // error page with a 200 status) was embedded anyway as bogus data,
        // corrupting the surrounding CSS/HTML so images/backgrounds simply
        // didn't render. Rather than trying to distinguish good snapshots
        // from bad ones, discard all of them site-wide; view.php and
        // download.php both regenerate on demand when missing.
        $DB->delete_records('files', [
            'component' => 'mod_learningapp',
            'filearea'  => 'localstorage',
        ]);
        $DB->delete_records('files', [
            'component' => 'mod_learningapp',
            'filearea'  => 'appcache',
        ]);

        upgrade_mod_savepoint(true, 2026090500, 'learningapp');
    }

    return true;
}
